name: kubjas
base: core18
version: '1.3'
summary: process scheduling daemon
description: |
  Kubjas is a background process that runs particular programs at particular intervals.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  # The debian-multiarch-triplet-provider-launch launcher: Enable DEBIAN_MULTIARCH_TRIPLET-like environment variable in the snap runtime
  # https://forum.snapcraft.io/t/the-debian-multiarch-triplet-provider-launch-launcher-enable-debian-multiarch-triplet-like-environment-variable-in-the-snap-runtime/11738
  debian-multiarch-triplet-provider-launch:
    source: https://github.com/Lin-Buo-Ren/debian-multiarch-triplet-provider-launch.git
    source-tag: v1.0.0
    plugin: dump
    stage:
      - bin/debian-multiarch-triplet-provider-launch
  kubjas:
    plugin: nil
    source: .
    stage-packages:
    - libconfig-inifiles-perl
    - libtime-period-perl
    - liblinux-inotify2-perl
    stage-snaps:
    - perl-launch
    override-build: |
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/bin
      install -m 755 kubjas.pl $SNAPCRAFT_PART_INSTALL/bin/kubjas

apps:
  kubjas:
    command: bin/kubjas
    command-chain:
    - bin/debian-multiarch-triplet-provider-launch
    - bin/perl-launch
    environment:
      LANG: C.UTF-8

